spring:
  redis:
    host: localhost
    port: 6379
  profiles:
    active: local

  h2:
    console:
      enabled: true

  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB


cloud:
  aws:
    credentials:
      access-key: AKIAZWIFHWL7LZ54JTUX
      secret-key: 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
    region:
      static: ap-northeast-2
    s3:
      bucket: carefully-bucket
    stack:
      auto: false

jwt:
  header: Authorization
  authorities-key: auth
  bearer-type: Bearer
  secret: c2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQtc2lsdmVybmluZS10ZWNoLXNwcmluZy1ib290LWp3dC10dXRvcmlhbC1zZWNyZXQK
  token-validity-in-seconds: 86400
  access-token-expire-time: 30 * 60 * 1000L
  refresh-token-expire-time : 7 * 24 * 60 * 60 * 1000L


logging:
  level:
    me.silvernine: DEBUG

coolsms:
  key: NCSQF38UHJMLWRBN
  secret: XWHVUXVBYEMUJZNBYBNUCQ6DR6OHW3XP
  phone: 010-4537-4551