name: Java CI/CD with Docker

on:
  push:
    branches:
      - feature/cicd
  pull_request:
    branches:
      - feature/cicd

env:
  NAME: ${{ secrets.DOCKERHUB_USERNAME }}
  REPO: carefully

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          token: ${{secrets.TOKEN_GITHUB}}
          submodules: true

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ env.NAME }}/${{ env.REPO }}:latest

  deploy:
    needs: build
    name: deploy
    runs-on: [ self-hosted, label-development ]
    steps:
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker run
        run: |
          docker stop ${{ env.REPO }} && docker rm ${{ env.REPO }} && docker rmi ${{ env.NAME }}/${{ env.REPO }}:latest
          docker run -d -p 80:8080 --name ${{ env.REPO }} --restart always ${{ env.NAME }}/${{ env.REPO }}:latest






